// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: school_events.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SchoolRegistered struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SchoolId string `protobuf:"bytes,1,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
}

func (x *SchoolRegistered) Reset() {
	*x = SchoolRegistered{}
	if protoimpl.UnsafeEnabled {
		mi := &file_school_events_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SchoolRegistered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchoolRegistered) ProtoMessage() {}

func (x *SchoolRegistered) ProtoReflect() protoreflect.Message {
	mi := &file_school_events_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchoolRegistered.ProtoReflect.Descriptor instead.
func (*SchoolRegistered) Descriptor() ([]byte, []int) {
	return file_school_events_proto_rawDescGZIP(), []int{0}
}

func (x *SchoolRegistered) GetSchoolId() string {
	if x != nil {
		return x.SchoolId
	}
	return ""
}

type SchoolSuspended struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SchoolId string `protobuf:"bytes,1,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
}

func (x *SchoolSuspended) Reset() {
	*x = SchoolSuspended{}
	if protoimpl.UnsafeEnabled {
		mi := &file_school_events_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SchoolSuspended) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchoolSuspended) ProtoMessage() {}

func (x *SchoolSuspended) ProtoReflect() protoreflect.Message {
	mi := &file_school_events_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchoolSuspended.ProtoReflect.Descriptor instead.
func (*SchoolSuspended) Descriptor() ([]byte, []int) {
	return file_school_events_proto_rawDescGZIP(), []int{1}
}

func (x *SchoolSuspended) GetSchoolId() string {
	if x != nil {
		return x.SchoolId
	}
	return ""
}

var File_school_events_proto protoreflect.FileDescriptor

var file_school_events_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31,
	0x22, 0x2f, 0x0a, 0x10, 0x53, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x49,
	0x64, 0x22, 0x2e, 0x0a, 0x0f, 0x53, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x53, 0x75, 0x73, 0x70, 0x65,
	0x6e, 0x64, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x49,
	0x64, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x67, 0x72, 0x7a, 0x65, 0x67, 0x61, 0x62, 0x2f, 0x57, 0x48, 0x5f, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x72, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_school_events_proto_rawDescOnce sync.Once
	file_school_events_proto_rawDescData = file_school_events_proto_rawDesc
)

func file_school_events_proto_rawDescGZIP() []byte {
	file_school_events_proto_rawDescOnce.Do(func() {
		file_school_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_school_events_proto_rawDescData)
	})
	return file_school_events_proto_rawDescData
}

var file_school_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_school_events_proto_goTypes = []any{
	(*SchoolRegistered)(nil), // 0: events.v1.SchoolRegistered
	(*SchoolSuspended)(nil),  // 1: events.v1.SchoolSuspended
}
var file_school_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_school_events_proto_init() }
func file_school_events_proto_init() {
	if File_school_events_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_school_events_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SchoolRegistered); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_school_events_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SchoolSuspended); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_school_events_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_school_events_proto_goTypes,
		DependencyIndexes: file_school_events_proto_depIdxs,
		MessageInfos:      file_school_events_proto_msgTypes,
	}.Build()
	File_school_events_proto = out.File
	file_school_events_proto_rawDesc = nil
	file_school_events_proto_goTypes = nil
	file_school_events_proto_depIdxs = nil
}
